### ISSUE TITLE
在win11下加载配置文件失败

### ISSUE THREAD

**Issue by mayflower-zc** [kricsleo/iconfonter#1]
<img width="1134" alt="error" src="https://github.com/kricsleo/iconfonter/assets/6245772/1af64761-4082-418b-b59d-0cf3329a1781">
<img width="418" alt="error2" src="https://github.com/kricsleo/iconfonter/assets/6245772/c7e970b0-8bc2-4323-913a-1488cd1c214c">

**Comment by kricsleo** [comment]
Thanks for the feedback! `v0.0.4` should fix your problem :)
