### ISSUE TITLE
多了一个“}”

### ISSUE THREAD

**Issue by mayflower-zc** [kricsleo/iconfonter#2]
<img width="1231" alt="error3" src="https://github.com/kricsleo/iconfonter/assets/6245772/b771aaf0-09b9-46a8-8a0c-52875ab5fd10">

**Comment by kricsleo** [comment]
Nice spot! But it doesn't seem to affect the download of the icon. And sure it will fixed in the next release! Thank you :)

**Comment by kricsleo** [comment]
Resolved in https://github.com/kricsleo/iconfonter/commit/4606914cbecb167d9cb5a1615a9f8e544e99c242, thanks🚀
